// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJytUGxwHdWTqqVqPLuqh0jJBOvMmZ0os',
    appId: '1:626549354220:web:57cdc48f0935ce779affc9',
    messagingSenderId: '626549354220',
    projectId: 'ecommerce-55e88',
    authDomain: 'ecommerce-55e88.firebaseapp.com',
    storageBucket: 'ecommerce-55e88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DJFWCaydMnDCXex1uu0oEs7HCWjHG8Y',
    appId: '1:626549354220:android:8ab6907bc56cdf909affc9',
    messagingSenderId: '626549354220',
    projectId: 'ecommerce-55e88',
    storageBucket: 'ecommerce-55e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaap4PAC4Ikk0-_Q0uYOx3XnSnT2kf90',
    appId: '1:626549354220:ios:7b8f2c98556b09639affc9',
    messagingSenderId: '626549354220',
    projectId: 'ecommerce-55e88',
    storageBucket: 'ecommerce-55e88.firebasestorage.app',
    iosBundleId: 'com.aacl.finalflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaap4PAC4Ikk0-_Q0uYOx3XnSnT2kf90',
    appId: '1:626549354220:ios:7b8f2c98556b09639affc9',
    messagingSenderId: '626549354220',
    projectId: 'ecommerce-55e88',
    storageBucket: 'ecommerce-55e88.firebasestorage.app',
    iosBundleId: 'com.aacl.finalflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJytUGxwHdWTqqVqPLuqh0jJBOvMmZ0os',
    appId: '1:626549354220:web:209b26d419f755479affc9',
    messagingSenderId: '626549354220',
    projectId: 'ecommerce-55e88',
    authDomain: 'ecommerce-55e88.firebaseapp.com',
    storageBucket: 'ecommerce-55e88.firebasestorage.app',
  );

// ...

}